/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eryk' at '25.04.18 18:21' with Gradle 2.10
 *
 * @author eryk, @date 25.04.18 18:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
